### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by MKhodagholi** [MahdiAsadolahzade/Ava#1]
دیپلویی برای پروژه انجام شده است؟
اگر انجام شده است لطفا در فایل readme پروژه اضافه کنید.

**Comment by MKhodagholi** [comment]
خیلی ممنون؛
یک سری مشکلات در پیاده سازی طرح هست؛ که خوب هست اصلاحشون کنید.

در صفحه آرشیو ها جدول شبیه طراحی تنظیم نشده است.

<img width="1148" alt="Screen Shot 2023-08-24 at 2 42 26 PM" src="https://github.com/MahdiAsadolahzade/Ava/assets/83423435/ba20807c-d197-474c-982c-08b41c8ff21b">

در منوی سمت راست هم آیکون ها در یک راستا نیستند.

<img width="159" alt="Screen Shot 2023-08-24 at 2 42 07 PM" src="https://github.com/MahdiAsadolahzade/Ava/assets/83423435/09832b01-0952-4c65-9685-d11d7a57310b">


در ضمن یک نکته به نظرم خوب هست اینجا بگم و اینکه موقعی که می‌خواهید پروژه‌ای را در ریپازوتوری پوش کنید، به هیچ عنوان دایرکتوری dist و node_modules رو پوش نکنید. این یک مورد هم بی زحمت اصلاح کنید.
( برای اینکار می‌تونید یه فایل به اسم gitignore. درست کنید و این دو تا دایرکتوری رو داخلش بنویسید و دیگر git این دو تارو track نمی‌کنه، برای اطلاع بیشتر یه سرچ کنید خوبه )

**Comment by MahdiAsadolahzade** [comment]
خیلی ممنون از لطف و توجهتون چشم روشون کار میکنم و درستشون میکنم خیلی ممنون از راهنماییتون
